meta:
  environment: bui-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: bui
    networks:
      - name: bui1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: bui1
  type: manual
  subnets:
  - range: 10.244.66.0/24
    name: bui1
    gateway: 10.244.66.1
    static:
      - 10.244.66.2 - 10.244.66.60

properties:
  bui:
    bosh_addr: https://192.168.50.4:25555